# storage:
#   s3:
#     region: eu-central-1
#     bucket: test-dsg105
# middleware:
#   storage:
#     - name: cloudfront
#       options:
#         baseurl: https://d2s7lmtiia5e0t.cloudfront.net/
#         #privatekey: /etc/docker/cloudfront/pk-ABCEDFGHIJKLMNOPQRST.pem
#         #keypairid: ABCEDFGHIJKLMNOPQRST

version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    region: eu-central-1
    bucket: test-dsg105
    encrypt: true
    secure: true
    v4auth: true
    #rootdirectory: /var/lib/registry
middleware:
  storage:
    - name: cloudfront
      options:
        baseurl: https://d2s7lmtiia5e0t.cloudfront.net/
        #privatekey: /etc/docker/cloudfront/pk-ABCEDFGHIJKLMNOPQRST.pem
        #keypairid: ABCEDFGHIJKLMNOPQRST
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3



